### ISSUE TITLE
Rename `Model.sample` to `Model.model`

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/multisignal-epi-inference#225]
This:
```python
self.kernel = NUTS(
    model=self.model,
    **nuts_args,
)
```
makes more sense than the current:

```python
self.kernel = NUTS(
    model=self.sample,
    **nuts_args,
)
```

**Comment by AFg6K7h4fhy2** [comment]
For clarification here, does this mean changing all function-name instances of `sample` to `model`? Or, instead, is the expected task that to create a new abstract method in `metaclass.py` to support the assignment `self.model = model`, where model is what is instantiated in each subclass (e.g. `RtInfectionsRenewalModel` or `HospitalAdmissionsModel`), possibly in their existing `sample` methods?

**Comment by damonbayer** [comment]
> For clarification here, does this mean changing all function-name instances of `sample` to `model`? Or, instead, is the expected task that to create a new abstract method in `metaclass.py` to support the assignment `self.model = model`, where model is what is instantiated in each subclass (e.g. `RtInfectionsRenewalModel` or `HospitalAdmissionsModel`), possibly in their existing `sample` methods?

The latter. It is a simple renaming of the `Model.sample` method to `Model.model` to make the `NUTS` call more readable and reflect our recent decision to generally not have models return anything.

**Comment by AFg6K7h4fhy2** [comment]
Updates on decision making...

Since modifying, in the code below, the `sample` call for forward simulation (i.e., `model1.sample(n_timepoints_to_simulate=30)` to `model1.model(n_timepoints_to_simulate=30)`) appears somewhat confusing, @damonbayer and myself have considered instead creating an alias such that `Model.sample` and `Model.model` operate similarly, but can be used in different contexts (see after code block).

```python
model1 = RtInfectionsRenewalModel(
    I0_rv=I0,
    gen_int_rv=gen_int,
    latent_infections_rv=latent_infections,
    infection_obs_process_rv=observed_infections,
    Rt_process_rv=rt,
)
# Sampling and fitting model 1 (with obs infections)
np.random.seed(2203)
with npro.handlers.seed(rng_seed=np.random.randint(1, 600)):
   model1_samp = model1.sample(n_timepoints_to_simulate=30)
```

To illustrate, in `metaclass.py`, the following works 

```python
self.kernel = NUTS(
    model=self.model,
    **nuts_args,
)
```

in addition to the first code block.
